### ISSUE TITLE
Colored text

### ISSUE THREAD

**Issue by FAXES** [FAXES/markdownconvert#3]
Have the option to add coloured text to the passed string

Proposed syntax;
```
[Colored text]{#FFFFFF}
```

**Comment by braxtongpoll** [comment]
oooo cute


maybe I add?

**Comment by braxtongpoll** [comment]
Added in https://github.com/FAXES/markdownconvert/pull/5

**Comment by FAXES** [comment]
Added
https://github.com/FAXES/markdownconvert/pull/5
